#!/usr/bin/env ruby
# frozen_string_literal: true

# Fails if the built site loads resources from third-party hosts without the visitor's consent.
#
# Scripts, iframes, stylesheets, images, media and fonts must come from this site itself.
# Google Analytics and YouTube are only allowed through the theme's consent handling
# (assets/theme/js/consent.js, _includes/youtube.html), which never puts their URLs into
# a src/href attribute of the generated HTML.
#
# Usage: ruby script/check-third-party.rb [site_dir]   (default: _site)

require "uri"
require "yaml"

SITE_DIR = ARGV.fetch(0, "_site")

# Absolute URLs to the site's own domain are first-party.
SITE_HOST = URI(YAML.safe_load_file("_config.yml", aliases: true).fetch("url")).host

# Old copy of the previous site that is still published; not generated by this theme.
IGNORED_PATHS = %r{\A#{Regexp.escape(SITE_DIR)}/docs/}

# Attributes that make the browser fetch a resource on page load.
RESOURCE_ATTRIBUTE = /<(script|iframe|img|source|video|audio|embed|object|link)\b[^>]*?\s(?:src|srcset|data|href)\s*=\s*["']\s*(https?:)?\/\/([^\/"'\s]+)/i
CSS_URL = /url\(\s*["']?(https?:)?\/\/([^\/"')\s]+)/i
CSS_IMPORT = /@import\s+(?:url\()?\s*["'](https?:)?\/\/([^\/"'\s]+)/i

# <link> relations that make the browser fetch or connect on page load.
FETCHING_LINK = /\brel\s*=\s*["'][^"']*\b(?:stylesheet|preload|modulepreload|prefetch|preconnect|dns-prefetch|icon|manifest)\b/i

failures = []

Dir.glob(File.join(SITE_DIR, "**", "*.{html,css}")).sort.each do |file|
  next if file.match?(IGNORED_PATHS)

  content = File.read(file, encoding: "UTF-8")
  content.each_line.with_index(1) do |line, number|
    line.scan(RESOURCE_ATTRIBUTE) do
      match = Regexp.last_match
      tag, host = match[1].downcase, match[3].downcase
      next if host == SITE_HOST
      next if tag == "link" && !line[match.begin(0)..].split(">", 2).first.match?(FETCHING_LINK)

      failures << "#{file}:#{number}: <#{tag}> loads a resource from #{host}"
    end
    [CSS_URL, CSS_IMPORT].each do |pattern|
      line.scan(pattern) do
        host = Regexp.last_match[2].downcase
        failures << "#{file}:#{number}: CSS loads a resource from #{host}" unless host == SITE_HOST
      end
    end
  end
end

if failures.empty?
  puts "No third-party resources found in #{SITE_DIR}."
else
  puts failures
  puts
  puts "#{failures.size} third-party resource(s) found. Self-host them or load them only after consent " \
       "(see _theme/jekyll-theme-fk/assets/theme/js/consent.js)."
  exit 1
end
